
version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-suflex}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-suflex}
      PGDATA: /data/postgres
    volumes:
       - .docker/data/postgres:/data/postgres
       - ./scripts/sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
    networks:
      - backend


  suflex-products:
    build:
      context: .
    volumes:
      - ./:/suflex/
      - ./environments/.env:/suflex/environments/.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: "bridge"